
clc;clear;
load('./data/month_var_ice.mat')
figure
set(gcf, 'position', [0 50 800 800]);
t = tiledlayout(2,1,'TileSpacing','Compact');

nexttile
hold on

% ===== 1. EKE 背景线 + 阴影区 =====

eke_upper = eke_mean + eke_clim_error;
eke_lower = eke_mean - eke_clim_error;

fill_area = fill([(1:365)'; (365:-1:1)'], ...
                 [eke_upper'; flip(eke_lower')], ...
                 [0.7 0.7 0.7], ...
                 'EdgeColor', 'none', 'FaceAlpha', 0.3);

h6 = plot(1:365, eke_mean, 'LineWidth', 3, ...
          'Color', [0.6, 0.6, 0.6], 'LineStyle', '--');

% ===== 2. MKE 曲线 + 工字误差棒 =====
mke_color = [0.00, 0.45, 0.74];
h1 = plot(dd - datenum('2013-12-31'), mke, ...
          'Color', mke_color, 'LineWidth', 4);
e1 = errorbar(dd - datenum('2013-12-31'), mke, mke_err, ...
    'o', ...
    'MarkerSize', 5, ...
    'MarkerEdgeColor', mke_color, ...
    'MarkerFaceColor', mke_color, ...
    'CapSize', 6, ...
    'Color', mke_color, ...
    'LineWidth', 2);

% ===== 3. SMKE 曲线 + 工字误差棒 =====
smke_color =  [0.85, 0.33, 0.10];
h2 = plot(dd - datenum('2013-12-31'), smke, ...
          'Color', smke_color, 'LineWidth', 4);

e2 = errorbar(dd - datenum('2013-12-31'), smke, smke_err, ...
    'o', ...
    'MarkerSize', 5, ...
    'MarkerEdgeColor', smke_color, ...
    'MarkerFaceColor', smke_color, ...
    'CapSize', 6, ...
    'Color', smke_color, ...
    'LineWidth', 2);

% ===== 4. 月平均 EKE 曲线 =====
eke_month_color = [0.47, 0.67, 0.19];
h5 = plot(dd - datenum('2013-12-31'), eke_month, ...
          'Color', eke_month_color, 'LineWidth', 2.5);

% ===== 5. 美化坐标轴与文字 =====
xlim([1, 365])
ylabel('KE [m^2/s^{2}]', 'FontSize', 16, 'FontWeight', 'bold')
set(gca, 'xtick', dd - datenum('2013-12-31'), ...
         'xticklabel', datestr(dd, 'mmm'))
set(gca, 'FontSize', 14, 'FontWeight', 'bold', 'FontName', 'Times')
text(5, 0.019, '(a)', 'FontSize', 16, 'FontWeight', 'bold')

% ===== 6. 添加图例（推荐）=====
legend([h1, h2, h5, h6], ...
       {'MKE', 'SMKE', 'EKE monthly mean', 'Climatological EKE'}, ...
       'Location', 'northeast', ...
       'FontSize', 12, 'Box', 'off')


clear
load ('/Users/chaijunwei/Documents/energyflux/2025-4-5/data/month_var_irm.mat')
nexttile
hold on

% === 配色定义 ===
eke_clim_color = [0.6, 0.6, 0.6];          % 灰色虚线
mke_color      = [0.00, 0.45, 0.74];       % 蓝色
smke_color     = [0.85, 0.33, 0.10];       % 红棕色
eke_color      = [0.47, 0.67, 0.19];       % 黄绿色

% === EKE climatology 背景阴影 + 均值线 ===
eke_upper = eke_mean + eke_clim_error;
eke_lower = eke_mean - eke_clim_error;
fill([(1:365)'; flipud((1:365)')], ...
     [eke_upper'; flipud(eke_lower')], ...
     eke_clim_color, 'FaceAlpha', 0.3, 'EdgeColor', 'none');
h6 = plot(1:365, eke_mean, 'LineWidth', 3, ...
          'Color', eke_clim_color, 'LineStyle', '--');

% === MKE 曲线 + 工字型误差棒 ===
h1 = plot(dd - datenum('2013-12-31'), mke, ...
          'Color', mke_color, 'LineWidth', 4);
e1 = errorbar(dd - datenum('2013-12-31'), mke, mke_err, ...
    'o', 'MarkerSize', 5, ...
    'MarkerEdgeColor', mke_color, ...
    'MarkerFaceColor', mke_color, ...
    'CapSize', 6, ...
    'Color', mke_color, 'LineWidth', 2);

% === SMKE 曲线 + 工字型误差棒 ===
h2 = plot(dd - datenum('2013-12-31'), smke, ...
          'Color', smke_color, 'LineWidth', 4);
e2 = errorbar(dd - datenum('2013-12-31'), smke, smke_err, ...
    'o', 'MarkerSize', 5, ...
    'MarkerEdgeColor', smke_color, ...
    'MarkerFaceColor', smke_color, ...
    'CapSize', 6, ...
    'Color', smke_color, 'LineWidth', 2);

% === 0.5 * EKE monthly line ===
h5 = plot(dd - datenum('2013-12-31'), 0.5 * eke_month, ...
          'Color', eke_color, 'LineWidth', 2);


% === 坐标/标签设置 ===
ylabel('KE [m^2/s^{2}]', 'FontSize', 16, 'FontWeight', 'bold')
xlim([1, 365])
ylim([0, 0.015])

set(gca, 'xtick', dd - datenum('2013-12-31'), ...
         'xticklabel', datestr(dd, 'mmm'), ...
         'FontSize', 14, 'FontWeight', 'bold', 'FontName', 'Times');

% ===== 5. 美化坐标轴与文字 =====
xlim([1, 365])
ylabel('KE [m^2/s^{2}]', 'FontSize', 16, 'FontWeight', 'bold')
set(gca, 'xtick', dd - datenum('2013-12-31'), ...
         'xticklabel', datestr(dd, 'mmm'))
set(gca, 'FontSize', 14, 'FontWeight', 'bold', 'FontName', 'Times')
text(5, 0.0115, '(b)', 'FontSize', 16, 'FontWeight', 'bold')
ylim([0 0.012])


legend([h1, h2, h5, h6], ...
       {'MKE', 'SMKE', 'EKE monthly mean', 'Climatological EKE'}, ...
       'Location', 'northeast', ...
       'FontSize', 12, 'Box', 'off')

text(30,0.001,'Irminger Sea','FontSize', 18, 'FontWeight', 'bold', 'FontName', 'Times')
text(30,0.015,'Iceland Basin','FontSize', 18, 'FontWeight', 'bold', 'FontName', 'Times')

print('-dpng','-r600','./figure/figure4.png')

